feat: Add deps & test in cargo
EyesCrypto-Insights/rust-by-example-vn pull request #12
Opened 2023-03-04 16:44 UTC by dungnguyen-art

1.     Translate src/cargo/deps.md
2.     Translate src/cargo/test.md

2023-03-08 08:17 UTC, HongThaiPham requested changes

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Hầu hết các chương trình đều phụ thuộc vào các thư viện. Nếu bạn đã từng tự tay quản lí các dependency, bạn biết nó vất vả như thế nào. Thật may mắn, hệ sinh thái ngôn ngữ Rust được chuẩn hóa với `ca
```suggestion
Hầu hết các chương trình đều phụ thuộc vào một vài thư viện nào đó. Nếu bạn đã từng tự tay quản lí các thư viện phụ thuộc này, bạn sẽ biết việc này có thể rất phiền toái. May mắn thay, hệ sinh thái Rust đi kèm với công cụ cargo! cargo có thể quản lý các phụ thuộc cho một dự án.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +# tạo nhị phân
```suggestion
# một tệp nhị phân
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Với phần còn lại của chương này, giả sử chúng ta đang tạo 1 hệ nhị phân, hơn là một thư viện, song mọi khái niệm là giống nhau.
```suggestion
Trong phần tiếp theo của chương này, giả sử rằng chúng ta đang tạo 1 tập nhị phân, chứ không phải một thư viện, song các khái niệm là giống nhau.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +`main.rs` là tệp tin gốc của project `foo` vừa được tạo.`Cargo.toml` là tệp tin chứa cấu hình cho `cargo` của project. Nếu bạn nhìn vào bên trong, bạn sẽ thấy một thứ như thế này:
```suggestion
`main.rs` là tệp tin gốc của dự án `foo` vừa được tạo - không có gì mới ở đây. `Cargo.toml` là tệp tin chứa cấu hình của `cargo` đối với dự án này. Nếu bạn xem bên trong tệp tin, bạn sẽ thấy giống như thế này: 
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Trường `name` bên dưới `[package]` xác định tên của project.Tên project cũng được sử dụng nếu bạn xuất bản crate lên `crates.io`. Nó cũng là tên của tệp nhị phân đầu ra khi được biên dịch.
```suggestion
Trường `name` bên dưới `[package]` xác định tên của dự án. Tên dự án cũng được sử dụng nếu bạn xuất bản crate lên `crates.io`. Nó cũng là tên của tệp nhị phân đầu ra khi được biên dịch.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Phần `[dependencies]` để bạn tùy ý thêm các dependency vào project của mình.
```suggestion
Phần `[dependencies]` để bạn tùy ý thêm các thư viện phụ thuộc vào dự án của mình.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Ví dụ, giả sử rằng chúng ta muốn chương trình của mình có một CLI tuyệt vời. Bạn có thể tìm kiếm rất nhiều package trên [crates.io](https://crates.io/) (Đăng ký chính thức của Rust). Một lựa chọn phổ
```suggestion
Ví dụ, giả sử rằng chúng ta muốn chương trình của mình có một CLI tuyệt vời. Bạn có thể tìm kiếm thấy rất nhiều package trên [crates.io](https://crates.io/) (Địa chỉ chính thức của hệ thống đăng ký gói của Rust). Một lựa chọn phổ biến là [clap](https://crates.io/crates/clap). Tại thời điểm viết bài này, phiên bản mới nhất của `clap` được công bố là `2.27.1`. Để thêm một phục thuộc cho chương trình của mình, chúng ta đơn giản chỉ cần thêm vào tệp `Cargo.toml` ở phía dưới phần `dependencies`:`clap = "2.27.1"`.  Và thế là xong. Bạn có thể bắt đầu sử dụng `clap` trong chương trình của mình.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +bar = { path = "../bar" } # từ một tệp dẫn trong hệ thống tệp cục bộ.
```suggestion
bar = { path = "../bar" } # đường dẫn trong hệ thống tệp cục bộ.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +`cargo` không chỉ là một trình quản lí các dependency. Tất cả các tùy chọn cấu hình đều có sẵn và được liệt kê trong [đặc tả định dạng](https://doc.rust-lang.org/cargo/reference/manifest.html) của `C
```suggestion
`cargo` không chỉ là một trình quản lí các phụ thuộc. Tất cả các tùy chọn cấu hình sẵn có đều được liệt kê trong [đặc tả định dạng](https://doc.rust-lang.org/cargo/reference/manifest.html) của `Cargo.toml`
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Để  build project của mình chúng ta có thể  thực thi bằng câu lệnh `cargo build` ở bất kì đâu trong thư mục project ( ngay cả trong các thư mục con). Chúng ta có thể chạy `cargo run` để build và run.
```suggestion
Để  build dự án, chúng ta có thể  thực thi lệnh `cargo build` ở bất kì đâu trong thư mục dự án (ngay cả trong các thư mục con). Chúng ta có thể sử dụng `cargo run` để build và chạy chương trình. Lưu ý rằng những câu lệnh này sẽ giải quyết tất cả các phụ thuộc, tải xuống các crate nếu cần, và build tất cả mọi thứ, bao gồm crate của bạn. ( Lưu ý rằng nó chỉ build lại những gì mà nó chưa được build trước đó, tương tự như `make`).
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/deps.md
> +Thì đấy! Đó là tất cả về dependency.
```suggestion
Trên đây là tất cả về quản lý các phụ thuộc.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/test.md
> +Từ các chương kiểm thử được liên kết phía trên, chúng ta sẽ biết cách để viết unit test và integration test.
```suggestion
Từ các chương kiểm thử trong liên kết phía trên, chúng ta sẽ biết cách để viết unit test và integration test.
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/test.md
> +Về mặt tổ chức, chúng tôi đặt các unit test bên trong các mô-đun, chúng sẽ test và integration test trong chính thư mục `tests/`:
```suggestion
Về mặt tổ chức, chúng ta đặt các unit test bên trong các module, chúng sẽ chạy kiểm tra và tích hợp kiểm thử trong chính thư mục `tests/`:
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/test.md
> +Mỗi tệp tin trong `tests` là một [integration test](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests) riêng biệt, tức là kiểm thử đó nhằm kiểm tra thư viện của bạn như
```suggestion
Mỗi tệp tin trong `tests` là một [integration test](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests) riêng biệt, tức là kiểm thử đó nhằm kiểm tra thư viện của bạn như thể nó được gọi từ một crate phụ thuộc. 
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/test.md
> +Bạn cũng có thể chạy kiểm thử với tên test cụ thể(`test_foo`):
```suggestion
Bạn cũng có thể chạy kiểm thử với tên của phép kiểm thử cụ thể(`test_foo`): 
```

2023-03-08 08:17 UTC, HongThaiPham commented on src/cargo/test.md
> +Cảnh báo: Cargo có thể chạy nhiều kiểm thử cùng lúc, vì thế hãy chắc chắn rằng không xảy ra tranh chấp tài nguyên.
```suggestion
Lưu ý: Cargo có thể chạy nhiều kiểm thử cùng lúc, vì thế hãy chắc chắn rằng không xảy ra tranh chấp tài nguyên. 
```

2023-03-08 18:31 UTC, dungnguyen-art commented on src/cargo/test.md
> +Cảnh báo: Cargo có thể chạy nhiều kiểm thử cùng lúc, vì thế hãy chắc chắn rằng không xảy ra tranh chấp tài nguyên.
vâng ạ, em cảm ơn a!

2023-03-12 15:20 UTC, nghuyenthevinh2000 approved these changes

2023-03-12 15:20 UTC, merged