translate(error): multiple_error_types and option_unwrap
EyesCrypto-Insights/rust-by-example-vn pull request #23
Opened 2023-03-07 15:31 UTC by tuannkhoi

2023-03-07 18:40 UTC, SkyTik requested changes

2023-03-07 18:40 UTC, SkyTik commented on src/error/option_unwrap.md
> +Chúng ta có thể kiểm tra điều này với string rỗng (`""`) giống như ta đã làm với nước chanh.
Nên là "empty string" hoặc "chuỗi rỗng" thay vì "string rỗng"

2023-03-07 18:40 UTC, SkyTik commented on src/error/option_unwrap.md
> +trong khi ta vẫn có thể `panic` nếu cần.
... giúp ta kiểm soát kết quả tốt hơn, trong khi vẫn giữ tùy chọn `panic` nếu cần.

2023-03-08 02:38 UTC, nghuyenthevinh2000 commented
pr này của bạn là close issue nào vậy?

2023-03-08 02:42 UTC, tuannkhoi commented on src/error/option_unwrap.md
> +Chúng ta có thể kiểm tra điều này với string rỗng (`""`) giống như ta đã làm với nước chanh.
mình đã đổi thành "empty string", thanks bạn

2023-03-08 02:42 UTC, tuannkhoi commented on src/error/option_unwrap.md
> +trong khi ta vẫn có thể `panic` nếu cần.
updated, thanks bạn 👍🏼

2023-03-08 02:46 UTC, tuannkhoi commented
> pr này của bạn là close issue nào vậy?

@nghuyenthevinh2000 mình đã update ở PR's description rồi, thanks bạn 👍🏼

2023-03-09 09:29 UTC, HongThaiPham commented on src/error/option_unwrap.md
> +Vì ta đang dùng Rust, hãy để compiler chỉ ra các trường hợp không có đồ uống.
```suggestion
Vì ta đang dùng Rust, hãy để trình biên dịch chỉ ra các trường hợp không có đồ uống.
```

2023-03-09 09:29 UTC, HongThaiPham commented on src/error/option_unwrap.md
> +Một `enum` tên là `Option<T>` trong thư viện `std` được sử dụng trong trường hợp có thể không có một phần tử nào.
```suggestion
Một `enum` tên là `Option<T>` trong thư viện `std` được sử dụng trong trường hợp có thể không có phần tử kiểu T.
```

2023-03-09 09:29 UTC, HongThaiPham commented on src/error/option_unwrap.md
> +nhưng xử lý ngầm định (`unwrap`) sẽ để lại cho ta một kết quả ít có ý nghĩa hơn so với việc xử lý rõ ràng.
```suggestion
nhưng xử lý ngầm định (`unwrap`) sẽ trả lại cho ta một kết quả ít có ý nghĩa hơn so với việc xử lý rõ ràng.
```

2023-03-09 14:10 UTC, tuannkhoi commented on src/error/option_unwrap.md
> +Vì ta đang dùng Rust, hãy để compiler chỉ ra các trường hợp không có đồ uống.
em nghĩ đây là terminology của programming nên giữ nguyên, k dịch

nếu anh thấy dịch ra hợp lý hơn thì em sẽ apply suggestion, anh nghĩ sao ạ?

2023-03-11 02:00 UTC, HongThaiPham commented on src/error/option_unwrap.md
> +Vì ta đang dùng Rust, hãy để compiler chỉ ra các trường hợp không có đồ uống.
đối với từ `complier` thì a nghĩ việc dịch ra thành `trình biên dịch` cũng vẫn có thể giúp người đọc cả dev và non-dev hiểu được đúng ý nghĩa chứ khg bị hiểu lầm sang ý nghĩa khác và mục đích của mình là translate nên từ nào có thể dịch ra được với sát nghĩa thì nên dịch.

để chủ nhật meet hỏi ý kiến mọi người thử nhé

2023-03-12 15:28 UTC, nghuyenthevinh2000 commented on src/error/option_unwrap.md
> +Vì ta đang dùng Rust, hãy để compiler chỉ ra các trường hợp không có đồ uống.
compiler (trình biên dịch)

2023-03-12 15:33 UTC, HongThaiPham approved these changes

2023-03-12 15:43 UTC, HongThaiPham approved these changes

2023-03-12 15:46 UTC, SkyTik approved these changes

2023-03-12 15:47 UTC, nghuyenthevinh2000 approved these changes

2023-03-12 15:47 UTC, merged