Translate abort_unwind.md, iter_result.md
EyesCrypto-Insights/rust-by-example-vn pull request #24
Opened 2023-03-07 18:18 UTC by SkyTik

- [ x]  abort_unwind.md
- [ x] iter_result.md

2023-03-09 02:59 UTC, HongThaiPham requested changes

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/abort_unwind.md
> +Phần trước đã mô tả cơ chế xử lí lỗi `panic`. Các thành phần code khác nhau có thể được thực thi một cách có điều kiện dựa trên các cài đặt `panic`. Các giá trị hiện có là `unwind` và `abort`.
```suggestion
Phần trước đã mô tả cơ chế xử lí lỗi `panic`. Các thành phần code khác nhau có thể được biên dịch một cách có điều kiện dựa trên các cài đặt `panic`. Các giá trị có thể là `unwind` và `abort`.
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/abort_unwind.md
> +Dựa trên ví dụ trước đó, chúng ta sử dụng các panic strategy để thực hiện các dòng code khác nhau.
```suggestion
Dựa trên ví dụ về nước chanh trước đó, chúng ta sử dụng các panic strategy để thực hiện các dòng code khác nhau.
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/abort_unwind.md
> +   // You shouldn't drink too much sugary beverages.
```suggestion
   // Bạn không nên uống quá nhiều đồ uống có đường.
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/iter_result.md
> +Một `Iter::map` có thể xảy ra lỗi, ví dụ:
```suggestion
Một `Iter::map` có thể không thành công, ví dụ:
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/iter_result.md
> +Đây là các cách để xử lí tình huống này.
```suggestion
Hãy thông qua từng bước của chiến lược để xứ lý tình huống này.
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/iter_result.md
> +## Bỏ qua các item bị lỗi bằng cách sử dụng `filter_map()`
```suggestion
## Bỏ qua các phần tử bị lỗi bằng cách sử dụng `filter_map()`
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/iter_result.md
> +## Thu thập các item bị lỗi với `map_err()` và `filter_map()`
```suggestion
## Thu thập các phần tử bị lỗi với `map_err()` và `filter_map()`
```

2023-03-09 02:59 UTC, HongThaiPham commented on src/error/iter_result.md
> +`Result` implements `FromIterator`, nên một vector chứa các kết quả (`Vec<Result<T, E>>`)
```suggestion
`Result` có triển khai `FromIterator`, nên một vector chứa các kết quả (`Vec<Result<T, E>>`)
```

2023-03-11 01:54 UTC, HongThaiPham approved these changes

2023-03-12 15:26 UTC, nghuyenthevinh2000 approved these changes

2023-03-12 15:26 UTC, merged