Translate hof.md methods.md
EyesCrypto-Insights/rust-by-example-vn pull request #40
Opened 2023-03-16 16:42 UTC by SkyTik

Close #33 

- [ ] hof.md
- [ ] methods.md

2023-03-17 00:57 UTC, HongThaiPham commented on src/fn/hof.md
> +    println!("Find the sum of all the squared odd numbers under 1000");
```suggestion
    println!("Tìm tổng của tất cả các số lẻ có bình phương nhỏ hơn 1000");
```

2023-03-17 01:02 UTC, HongThaiPham commented on src/fn/methods.md
> +Một số function được kết nối với một loại (type) cụ thể. Có hai dạng:
```suggestion
Một số function được liên kết với một kiểu dữ liệu (type) cụ thể. Có hai dạng là:
```

2023-03-17 01:03 UTC, HongThaiPham commented on src/fn/methods.md
> +nghĩa trên một loại, trong khi các phương thức là các hàm liên quan được
```suggestion
nghĩa trên một kiểu một cách chung chung, trong khi các phương thức là các hàm liên quan nhưng được
```

2023-03-17 01:03 UTC, HongThaiPham commented on src/fn/methods.md
> +được gọi trên một thể hiện (instance) cụ thể của một loại.
```suggestion
được gọi trên một thể hiện (instance) cụ thể của một kiểu.
```

2023-03-17 01:04 UTC, HongThaiPham commented on src/fn/methods.md
> +    // một loại cụ thể là Point
```suggestion
    // một kiểu cụ thể là struct Point
```

2023-03-17 01:06 UTC, HongThaiPham commented on src/fn/methods.md
> +    // `&self` trỏ tới `self: &Self`, trong đó `Self` là loại
```suggestion
    // `&self` là cú pháp viết tắt của `self: &Self`, trong đó `Self` là kiểu
```

2023-03-17 01:07 UTC, HongThaiPham commented on src/fn/methods.md
> +        // `self` cung cấp truy cập vào các fields của struct thông qua toán tử "."
```suggestion
        // sử dụng `self` cho phép ta truy cập vào các fields của struct thông qua toán tử dấu chấm "."
```

2023-03-17 01:08 UTC, HongThaiPham commented on src/fn/methods.md
> +        // `abs` là một phương thức `f64` trả về giá trị tuyệt đối của đối tượng gọi
```suggestion
        // `abs` là một phương thức của kiểu dữ liệu `f64` trả về giá trị tuyệt đối của đối tượng gọi
```

2023-03-17 01:09 UTC, HongThaiPham commented on src/fn/methods.md
> +    // `&mut self` trỏ tới `self: &mut Self`
```suggestion
    // `&mut self` là cú pháp viết tắt của `self: &mut Self`
```

2023-03-17 01:10 UTC, HongThaiPham commented on src/fn/methods.md
> +// `Pair` sở hữu các tài nguyên: hai số int trên vùng nhớ heap
```suggestion
// `Pair` sở hữu các tài nguyên: hai số nguyên 32 bit trên vùng nhớ heap 
```

2023-03-17 01:11 UTC, HongThaiPham commented on src/fn/methods.md
> +    // `self` trỏ tới `self: Self`
```suggestion
    // `self` là viết tắt của `self: Self`
```

2023-03-17 01:14 UTC, HongThaiPham commented on src/fn/methods.md
> +    // Error! Previous `destroy` call "consumed" `pair`
```suggestion
    // Error! phương thức `destroy` được gọi trước đó đã "tiêu thụ" `pair`
```

2023-03-19 15:29 UTC, nghuyenthevinh2000 requested changes

2023-03-19 15:29 UTC, nghuyenthevinh2000 commented on src/fn/methods.md
> +// Triển khai tất cả các fucntion & method liên quan đến `Point`
```suggestion
// Triển khai tất cả các function & method liên quan đến `Point`
```

2023-03-19 15:35 UTC, nghuyenthevinh2000 approved these changes

2023-03-19 15:35 UTC, merged