Patch 4
EyesCrypto-Insights/rust-by-example-vn pull request #41
Opened 2023-03-17 08:45 UTC by phongnguyen2012

update ngày 17/3/2023

2023-03-17 09:50 UTC, phongnguyen2012 commented
ngày 17/03/2023

2023-03-17 09:52 UTC, phongnguyen2012 reviewed
17/03/2023

2023-03-17 12:49 UTC, HongThaiPham commented on src/fn/closures.md
file này sao nội dung khác vậy bạn ơi
https://github.com/rust-lang/rust-by-example/blob/master/src/fn/closures.md

2023-03-19 15:09 UTC, nghuyenthevinh2000 commented
1. https://github.com/rust-lang/rust-by-example/blob/master/src/fn/diverging.md
2.  https://github.com/rust-lang/rust-by-example/blob/master/src/fn/closures.md
3.

2023-03-19 15:27 UTC, nghuyenthevinh2000 requested changes

2023-03-19 15:27 UTC, nghuyenthevinh2000 commented on src/fn/diverging.md
> +// Trong Rust, diverging funtion thường được sử dụng trong trường hợp xử lý lỗi.
```suggestion
// Trong Rust, diverging function thường được sử dụng trong trường hợp xử lý lỗi. 
```

2023-03-19 15:27 UTC, nghuyenthevinh2000 commented on src/fn/diverging.md
> +// Hàm foo() không có giá trị trả về nhưng thay vào đó, nó kích hoạt một sử dụng panic!() để dừng chương trình.
```suggestion
// Hàm foo() không có giá trị trả về nhưng thay vào đó, nó kích hoạt hàm panic!() để dừng chương trình. 
```

2023-03-31 08:50 UTC, phongnguyen2012 commented
Closes: #19 #32 
[result_alias.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/result/result_alias.md)
[result_map.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/result/result_map.md)
[closures.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/fn/closures.md)
[diverging.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/fn/diverging.md)

2023-03-31 14:17 UTC, duonghb53 commented on src/scope/lifetime/methods.md
Anh @phongnguyen2012 thêm lại 2 file này như cũ nhé

2023-03-31 14:17 UTC, duonghb53 commented on src/scope/lifetime/static_lifetime.md
Anh @phongnguyen2012 thêm lại 2 file này như cũ nhé

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +Khi chúng ta muốn sử dụng lại một kiểu Result cụ thể nhiều lần thì làm sao?
```suggestion
Khi chúng ta muốn tái sử dụng một kiểu `Result` cụ thể nhiều lần thì làm như thế nào?
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +Hãy nhớ rằng Rust cho phép chúng ta tạo [aliases][typealias]. Conveniently,
```suggestion
Hãy nhớ rằng Rust cho phép chúng ta tạo [aliases][typealias]. 
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +Ở mức độ module, việc tạo bí danh có thể rất hữu ích. Các lỗi được tìm thấy trong một module cụ thể thường có cùng kiểu Err,
```suggestion
Ở mức độ module, việc tạo bí danh có thể rất hữu ích. Các lỗi được tìm thấy trong một module cụ thể thường có cùng kiểu `Err`,
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +do đó một bí danh duy nhất có thể ngắn gọn định nghĩa tất cả các Result liên quan.
```suggestion
do đó một bí danh duy nhất có thể ngắn gọn định nghĩa tất cả các `Result` liên quan. 
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +Việc này rất hữu ích đến mức thư viện std cung cấp sẵn một bí danh cho việc này: [`io::Result`][io_result]!
```suggestion
Việc này rất hữu ích đến mức thư viện `std` cung cấp sẵn một bí danh cho việc này: [`io::Result`][io_result]!
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +// Định nghĩa một bí danh chung cho Result với kiểu lỗi ParseIntError.
```suggestion
// Định nghĩa một bí danh chung cho `Result` với kiểu lỗi `ParseIntError`.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_alias.md
> +// Sử dụng bí danh trên để tham chiếu đến kiểu Result cụ thể của chúng ta.
```suggestion
// Sử dụng bí danh trên để tham chiếu đến kiểu `Result` cụ thể của chúng ta.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_map.md
> +Khi xảy ra lỗi trong hàm `multiply` của ví dụ trước, sử dụng panic không tạo ra mã nguồn vững chắc.
```suggestion
Khi xảy ra lỗi trong hàm `multiply` của ví dụ trước, sử dụng panic không tạo ra mã nguồn mạnh mẽ. 
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_map.md
> +chúng ta tìm kiểu lỗi trong: [`parse()`][parse], Được thực hiện bằng cách sử dụng
```suggestion
chúng ta tìm kiểu lỗi trong [`parse()`][parse], Được thực hiện bằng cách triển khai trait
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_map.md
> +[`FromStr`][from_str] trait for [`i32`][i32]. Kết quả, kiểu `Err` được xác định như sau: [`ParseIntError`][parse_int_error].
```suggestion
[`FromStr`][from_str] cho [`i32`][i32]. Kết quả là, kiểu `Err` được xác định là kiểu [`ParseIntError`][parse_int_error].
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_map.md
> +[`Result`][result] chứa một danh sách đầy đủ..
```suggestion
[`Result`][result] chứa một danh sách đầy đủ.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_map.md
> +May mắn thay, các phương thức `Option`'s `map`, `and_then` và nhiều phương thức khác cũng được cài đặt cho Result.
```suggestion
May mắn thay, các phương thức `Option`'s `map`, `and_then` và nhiều phương thức khác cũng được cài đặt cho `Result`.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/error/result/result_map.md
> +// Giống với `Option`, chúng ta có thể sử dụng các phương thức ghép kết quả như `map()`.
```suggestion
// Giống với `Option`, chúng ta có thể sử dụng các phương thức kết hợp như `map()`.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +Closures là các hàm có thể nắm giữ môi trường bao quanh. Ví dụ, closure nắm giữ biến `x`:
```suggestion
Closures là các hàm có thể capture môi trường bao quanh. Ví dụ, closure capture biến `x`:
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +Gọi một closure hoàn toàn giống như gọi một hàm..
```suggestion
Gọi một closure hoàn toàn giống như gọi một hàm.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +Tuy nhiên, cả kiểu dữ liệu đầu vào và đầu ra *can* được suy luận và tên biến đầu vào *must* được chỉ định.
```suggestion
Tuy nhiên, cả kiểu dữ liệu đầu vào và đầu ra có thể được suy luận và tên biến đầu vào phải được chỉ định.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +* Sử dụng `||` thay vì `()` để bao quanh biến đầu vào..
```suggestion
* Sử dụng `||` thay vì `()` để bao quanh biến đầu vào.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +* Khả năng bắt được các biến môi trường bên ngoài (outer environment variables).
```suggestion
* Khả năng capture được các biến môi trường bên ngoài (outer environment variables).
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +    // được gán cho các biến được đặt tên phù hợp..
```suggestion
    // được gán cho các biến được đặt tên phù hợp.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/fn/closures.md
> +    // Một khi kiểu dữ liệu của closure đã được suy luận, thì nó không thể được suy luận lại với một kiểu dữ liệu khác.
```suggestion
    // Một khi kiểu dữ liệu của closure đã được suy ra, thì nó không thể được suy ra lại với một kiểu dữ liệu khác.
```

2023-04-01 04:30 UTC, duonghb53 commented on src/scope/lifetime/methods.md
@phongnguyen2012 em thấy a resolved nhưng chưa add file?

2023-04-02 15:14 UTC, duonghb53 commented on src/fn/closures.md
> +Tuy nhiên, cả kiểu dữ liệu đầu vào và đầu ra *can* được suy luận và tên biến đầu vào *must* được chỉ định.
```suggestion
Tuy nhiên, cả kiểu dữ liệu đầu vào và đầu ra có thể được suy luận và tên biến đầu vào phải được chỉ định.
```

2023-04-02 15:17 UTC, duonghb53 approved these changes
LGTM

2023-04-02 15:19 UTC, HongThaiPham approved these changes

2023-04-02 15:21 UTC, nghuyenthevinh2000 approved these changes

2023-04-02 15:21 UTC, merged