add alt_key_types.md & hashset.md
EyesCrypto-Insights/rust-by-example-vn pull request #95
Opened 2023-04-06 05:30 UTC by dungnguyen-art

Closes: #82 

- [ ] Translate alt_key_types.md
- [ ] hashset.md

2023-04-06 16:03 UTC, SkyTik requested changes

2023-04-06 16:48 UTC, SkyTik commented on src/std/hash/alt_key_types.md
> +Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại contained của chúng cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu `T` triển khai `Hash`.
```suggestion
Tất cả các lớp collection sẽ triển khai Eq và Hash nếu loại được chứa bên trong cũng được triển khai tương ứng Eq và Hash. Ví dụ, Vec<T> sẽ triển khai Hash nếu T triển khai Hash.
```

2023-04-06 16:49 UTC, SkyTik commented on src/std/hash/alt_key_types.md
> +Để  hiểu hơn về cách `struct` được sử dụng trong `HashMap`, hãy thử tạo một hệ thống logon đơn giản:
```suggestion
Để hiểu hơn về cách struct được sử dụng trong HashMap, hãy thử tạo một hệ thống đăng nhập đơn giản:
```

2023-04-06 16:50 UTC, SkyTik commented on src/std/hash/hashset.md
> +"Ý nghĩa của việc đó là gì?" bạn hỏi. "Tổi chỉ có thể lưu trữ các key trong `Vec`".
```suggestion
"Ý nghĩa của việc đó là gì?" bạn hỏi. "Tôi chỉ cần lưu trữ các key trong Vec".
```

2023-04-06 16:50 UTC, SkyTik commented on src/std/hash/hashset.md
> +Nếu bạn chèn một giá trị đã có trong `HashSet`, (Nghĩa là giá trị mới bằng với giá trị hiện tại và cả hai đều có cùng hàm hash), thì giá trị mới sẽ thay thế giá trị cũ.
```suggestion
Nếu bạn thêm vào một giá trị đã có trong `HashSet`, (Nghĩa là giá trị mới bằng với giá trị hiện tại và cả hai đều có cùng hàm hash), thì giá trị mới sẽ thay thế giá trị cũ.
```

2023-04-07 01:30 UTC, dungnguyen-art commented on src/std/hash/alt_key_types.md
> +Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại contained của chúng cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu `T` triển khai `Hash`.
Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại được chứa bên trong cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu T triển khai `Hash`.

2023-04-07 01:31 UTC, dungnguyen-art commented on src/std/hash/alt_key_types.md
> +Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại contained của chúng cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu `T` triển khai `Hash`.
```suggestion
Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại contained của chúng cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu `T` triển khai `Hash`.
```

2023-04-07 01:34 UTC, dungnguyen-art commented on src/std/hash/alt_key_types.md
> +Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại contained của chúng cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu `T` triển khai `Hash`.
```suggestion
Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại được chứa bên trong cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, `Vec<T>` sẽ triển khai `Hash` nếu `T` triển khai `Hash`.
```

2023-04-07 11:07 UTC, HongThaiPham commented on src/std/hash/alt_key_types.md
> +Bất kì kiểu nào triển khai trait của `Eq` và `Hash` đều có thể là một key trong `HashMap`. Điều này bao gồm:
```suggestion
Bất kì kiểu nào triển khai trait của `Eq` và `Hash` đều có thể là một key trong `HashMap`. Bao gồm:
```

2023-04-07 11:10 UTC, HongThaiPham commented on src/std/hash/alt_key_types.md
> +Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu loại được chứa bên trong cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, Vec<T> sẽ triển khai `Hash` nếu T triển khai `Hash`.
```suggestion
Tất cả các lớp collection sẽ triển khai `Eq` và `Hash` nếu kiểu được chứa bên trong cũng được triển khai tương ứng `Eq` và `Hash`. Ví dụ, Vec<T> sẽ triển khai `Hash` nếu T triển khai `Hash`.
```

2023-04-07 11:12 UTC, HongThaiPham commented on src/std/hash/alt_key_types.md
> +Trình biên dịch sẽ làm phần còn lại. Nếu bạn muốn kiểm soát nhiều hơn các chi tiết, bạn có thể tự triển khai `Eq` và/hoặc `Hash`. Hướng dẫn này không đề cập đến các chi tiết cụ thể của việc triển kha
```suggestion
Trình biên dịch sẽ làm phần còn lại. Nếu bạn muốn kiểm soát cụ thể hơn, bạn có thể tự triển khai `Eq` và/hoặc `Hash`. Hướng dẫn này không đề cập đến các chi tiết cụ thể của việc triển khai `Hash`.
```

2023-04-07 11:14 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +Hãy coi `HashSet` là một `HashMap` nơi chúng ta chỉ quan tâm đến các key( `HashSet<T>` thực tế chỉ là một wrapper(bao bọc) xung quanh `HashMap<T,()>`).
```suggestion
`HashSet` được coi như là một `HashMap` nếu chúng ta chỉ quan tâm đến các key( `HashSet<T>` thực tế chỉ là một wrapper(bao bọc) xung quanh `HashMap<T,()>`).
```

2023-04-07 11:16 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +"Ý nghĩa của việc đó là gì?" bạn hỏi. "Tôi chỉ cần lưu trữ các key trong Vec".
```suggestion
Bạn sẽ hỏi "Ý nghĩa của việc này là gì?". "Tôi có thể đơn giản là lưu trữ các key trong Vec".
```

2023-04-07 11:18 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +Tính năng độc đáo của `HashSet` là nó đảm bảo không có các phần tử trùng lặp. Đó là hợp đồng mà bất kì một collection set nào cũng đáp ứng.`HashSet` chỉ là một triển khai. (Xem thêm: [BTreeSet](https
```suggestion
Điểm đặc biệt của `HashSet` là nó đảm bảo không có các phần tử trùng lặp. Đó là điều mà bất kì một collection set nào cũng đáp ứng.`HashSet` chỉ là một triển khai của nó (collection). (Xem thêm: [BTreeSet](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html))
```

2023-04-07 11:19 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +Nếu bạn thêm vào một giá trị đã có trong `HashSet`, (Nghĩa là giá trị mới bằng với giá trị hiện tại và cả hai đều có cùng hàm hash), thì giá trị mới sẽ thay thế giá trị cũ.
```suggestion
Nếu bạn thêm vào một giá trị đã tồn tại trong `HashSet`, (Nghĩa là giá trị mới bằng với giá trị  đã có và cả hai đều có cùng hàm hash), thì giá trị mới sẽ thay thế giá trị cũ.
```

2023-04-07 11:22 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +Điều này thật hữu ích khi bạn không bao giờ muốn nhiều hơn một thứ gì đó hoặc khi bạn muốn biết liệu bạn đã có thứ gì đó chưa.
```suggestion
Điều này thật hữu ích khi bạn không muốn có nhiều hơn một thứ gì đó hoặc khi bạn muốn biết liệu bạn đã có thứ gì đó chưa.
```

2023-04-07 11:22 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +Nhưng các set nó có thể làm nhiều hơn thế.
```suggestion
Nhưng các set còn có thể làm nhiều hơn thế.
```

2023-04-07 11:23 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +- `symmetric_difference`: lấy tất cả các phần tử  chỉ xuất hiện trong tập này nhưng không xuất hiện trong tập kia.
```suggestion
- `symmetric_difference`: lấy tất cả các phần tử chỉ xuất hiện trong tập này nhưng không xuất hiện trong tập kia. 
```

2023-04-07 11:23 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +- `union`: lấy tất cả các phần tử  chỉ xuất hiện một lần trong cả hai tập.
```suggestion
- `union`: lấy tất cả các phần tử chỉ xuất hiện một lần trong cả hai tập.
```

2023-04-07 11:24 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +    // Điều này sẽ in [1]
```suggestion
    // Mã sau này sẽ in ra [1]
```

2023-04-07 11:25 UTC, HongThaiPham commented on src/std/hash/hashset.md
> +
(Các ví dụ đã được điều chỉnh theo [documentation.](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.difference))

2023-04-09 14:26 UTC, HongThaiPham approved these changes

2023-04-09 14:35 UTC, merged